namespace ContextoDePagamento.Dominio.Enumeradores
{
    public enum ELogradouro
    {
        aeroporto = 0,
        alameda = 1,
        area = 2,
        avenida = 3,
        campo = 4,
        chacara = 5,
        colonia = 6,
        condominio = 7,
        conjunto = 8,
        distrito = 9,
        esplanada = 10,
        estacao = 11,
        estrada = 12,
        favela = 13,
        fazenda = 14,
        feira = 15,
        jardim = 16,
        ladeira = 17,
        lago = 18,
        lagoa = 19,
        largo = 20,
        loteamento = 21,
        morro = 22,
        núcleo = 23,
        parque = 24,
        passarela = 25,
        pátio = 26,
        praça = 27,
        quadra = 28,
        recanto = 29,
        residencial = 30,
        rodovia = 31,
        rua = 32,
        setor = 33,
        sitio = 34,
        travessa = 35,
        trecho = 36,
        trevo = 37,
        vale = 38,
        vereda = 39,
        via = 40,
        viaduto = 41,
        viela = 42,
        vila = 43
    }
}